"""Compute a single atom, compute the Laplace approximation to the posterior at that atom.

The observed data are always defined to be the noise-free data generated by the
chosen atom. Therefore, at the chosen atom, the residual is zero and the exact
Hessian of the Gaussian log likelihood is

    d^2 log p(data | theta) / d theta^2 = d^2 log p(theta | data) / d theta^2 = -J.T @ J / sigma**2,

where ``J`` is the analytic Jacobian of the forward map with respect to
``theta = (x0, depth, R, amplitude)``.

The atom, noise level, scene path, regularisation, output path, and optional
finite-difference check are all chosen directly in ``main``.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

import numpy as np

from bayesian_gpr import Atom, Scene
from bayesian_gpr.forward import render_atom


BASIN_DIR = Path(__file__).resolve().parent
DATA_DIR = BASIN_DIR / "data"

PARAMETER_NAMES = ("x0", "depth", "R", "amplitude")


@dataclass(frozen=True)
class CurvatureResult:
    """Store the outputs of the one-atom curvature calculation.

    Attributes:
        data: Synthetic data generated by the chosen atom.
        rendered: Forward-map output evaluated at the chosen atom.
        residual: Difference between ``rendered`` and ``data``.
        jacobian: Analytic forward-map Jacobian with shape ``(Nt * Nx, 4)``.
        derivative_images: One derivative image per atom parameter.
        gradient_log_likelihood: Gradient of the Gaussian log likelihood.
        negative_hessian: Negative Hessian of the log likelihood.
        hessian_log_likelihood: Hessian of the log likelihood.
        covariance: Moore--Penrose inverse of the negative Hessian.
        precision_eigenvalues: Eigenvalues of the negative Hessian.
        condition_number: Condition number of the negative Hessian.
    """

    data: np.ndarray
    rendered: np.ndarray
    residual: np.ndarray
    jacobian: np.ndarray
    derivative_images: np.ndarray
    gradient_log_likelihood: np.ndarray
    negative_hessian: np.ndarray
    hessian_log_likelihood: np.ndarray
    covariance: np.ndarray
    precision_eigenvalues: np.ndarray
    condition_number: float


def ricker_and_derivative(
    tau: np.ndarray,
    f0: float,
) -> tuple[np.ndarray, np.ndarray]:
    """Return the Ricker wavelet and its derivative with respect to time offset.

    Args:
        tau: Time offsets in seconds.
        f0: Centre frequency in Hz.

    Returns:
        Ricker-wavelet values and their derivatives with respect to ``tau``.
    """
    c_squared = (np.pi * f0) ** 2
    u = c_squared * tau**2
    exp_minus_u = np.exp(-u)

    wavelet = (1.0 - 2.0 * u) * exp_minus_u
    wavelet_derivative = (
        2.0 * c_squared * tau * (2.0 * u - 3.0) * exp_minus_u
    )
    return wavelet, wavelet_derivative


def analytic_atom_jacobian(
    atom: Atom,
    scene: Scene,
) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """Render one atom and compute the analytic forward-map Jacobian.

    The parameter order is ``(x0, depth, R, amplitude)``. Each column of the
    Jacobian is the vectorised derivative image for one parameter.

    Args:
        atom: Atom at which to evaluate the forward map and its derivatives.
        scene: Scene supplying the grid, wavelet, and soil parameters.

    Returns:
        Rendered one-atom B-scan, analytic Jacobian, and derivative images.
    """
    x_axis = np.asarray(scene.grid.x_axis, dtype=float)
    t_axis = np.asarray(scene.grid.t_axis, dtype=float)
    velocity = float(scene.soil.v)
    alpha = float(scene.soil.alpha)
    f0 = float(scene.wavelet.f0)

    effective_depth = float(atom.depth + atom.R)
    if effective_depth <= 0.0:
        raise ValueError("Atom depth + radius must be positive")
    if velocity <= 0.0:
        raise ValueError("Soil velocity must be positive")

    horizontal_offset = x_axis - float(atom.x0)
    slant_range = np.sqrt(effective_depth**2 + horizontal_offset**2)

    spread = np.sqrt(effective_depth / slant_range)
    absorption = np.exp(-2.0 * alpha * slant_range)
    attenuation = spread * absorption

    # This is the same travel-time locus used by render_atom.
    travel_time = (
        (2.0 / velocity) * (slant_range - effective_depth)
        + (2.0 * atom.depth / velocity)
    )
    tau = t_axis[:, None] - travel_time[None, :]

    wavelet, wavelet_derivative = ricker_and_derivative(tau, f0)
    amplitude = float(atom.amplitude)
    rendered = amplitude * attenuation[None, :] * wavelet

    # Derivatives of log(B), where
    # B = sqrt(effective_depth / slant_range) * exp(-2 alpha slant_range).
    dlog_attenuation_dx0 = horizontal_offset * (
        0.5 / slant_range**2 + 2.0 * alpha / slant_range
    )
    dlog_attenuation_deffective_depth = (
        0.5 / effective_depth
        - 0.5 * effective_depth / slant_range**2
        - 2.0 * alpha * effective_depth / slant_range
    )

    # Since tau = t - travel_time, these are the derivatives of tau.
    dtau_dx0 = 2.0 * horizontal_offset / (velocity * slant_range)
    dtau_ddepth = -2.0 * effective_depth / (velocity * slant_range)
    dtau_dR = (2.0 / velocity) * (
        1.0 - effective_depth / slant_range
    )

    common = amplitude * attenuation[None, :]

    dA_dx0 = common * (
        wavelet * dlog_attenuation_dx0[None, :]
        + wavelet_derivative * dtau_dx0[None, :]
    )
    dA_ddepth = common * (
        wavelet * dlog_attenuation_deffective_depth[None, :]
        + wavelet_derivative * dtau_ddepth[None, :]
    )
    dA_dR = common * (
        wavelet * dlog_attenuation_deffective_depth[None, :]
        + wavelet_derivative * dtau_dR[None, :]
    )
    dA_damplitude = attenuation[None, :] * wavelet

    derivative_images = np.stack(
        (dA_dx0, dA_ddepth, dA_dR, dA_damplitude),
        axis=0,
    )
    jacobian = derivative_images.reshape(4, -1).T

    return rendered, jacobian, derivative_images


def finite_difference_atom_jacobian(
    atom: Atom,
    scene: Scene,
    step_sizes: np.ndarray,
) -> np.ndarray:
    """Compute a central-finite-difference Jacobian for validation.

    Args:
        atom: Atom at which to evaluate the finite-difference Jacobian.
        scene: Scene supplying the forward-model parameters.
        step_sizes: Positive step sizes for ``(x0, depth, R, amplitude)``.

    Returns:
        Finite-difference Jacobian with shape ``(Nt * Nx, 4)``.
    """
    step_sizes = np.asarray(step_sizes, dtype=float)
    if step_sizes.shape != (4,) or np.any(step_sizes <= 0.0):
        raise ValueError("step_sizes must contain four positive values")

    theta = np.array(
        [atom.x0, atom.depth, atom.R, atom.amplitude],
        dtype=float,
    )
    jacobian = np.empty((scene.grid.Nt * scene.grid.Nx, 4), dtype=float)

    def make_atom(values: np.ndarray) -> Atom:
        """Return an atom from a parameter vector."""
        return Atom(
            x0=float(values[0]),
            depth=float(values[1]),
            R=float(values[2]),
            amplitude=float(values[3]),
            eps_r=atom.eps_r,
        )

    for parameter_index, step_size in enumerate(step_sizes):
        plus = theta.copy()
        minus = theta.copy()
        plus[parameter_index] += step_size
        minus[parameter_index] -= step_size

        if parameter_index == 2 and minus[parameter_index] < 0.0:
            raise ValueError("Radius finite-difference step crosses R = 0")

        image_plus = render_atom(
            make_atom(plus),
            scene.grid,
            scene.wavelet,
            scene.soil,
        )
        image_minus = render_atom(
            make_atom(minus),
            scene.grid,
            scene.wavelet,
            scene.soil,
        )
        derivative_image = (image_plus - image_minus) / (2.0 * step_size)
        jacobian[:, parameter_index] = derivative_image.ravel()

    return jacobian


def compute_atom_curvature(
    sigma: float,
    atom: Atom,
    scene: Scene,
    *,
    regularization: float = 0.0,
) -> CurvatureResult:
    """Compute the one-atom Jacobian, Hessian, and local covariance.

    The data are always generated from the same atom at which the derivatives
    are evaluated:

        data = A(atom).

    Consequently, the residual is zero and the exact Hessian of the Gaussian
    log likelihood is ``-J.T @ J / sigma**2``. The interior uniform priors and
    exponential radius prior used in ``birth_mcmc.py`` add no Hessian curvature.

    Args:
        sigma: Standard deviation of the additive Gaussian noise model.
        atom: Representative atom defining both the synthetic data and the
            point at which curvature is calculated.
        scene: Scene supplying the grid, wavelet, and soil parameters.
        regularization: Nonnegative diagonal ridge added to the negative
            Hessian before computing its inverse.

    Returns:
        One-atom curvature results.
    """
    if sigma <= 0.0 or not np.isfinite(sigma):
        raise ValueError("sigma must be finite and positive")
    if regularization < 0.0:
        raise ValueError("regularization must be nonnegative")

    # The analytic renderer and render_atom should agree. We use render_atom to
    # define the synthetic observed data exactly as the model code does.
    data = render_atom(atom, scene.grid, scene.wavelet, scene.soil)
    rendered, jacobian, derivative_images = analytic_atom_jacobian(atom, scene)
    residual = rendered - data

    gradient = -(jacobian.T @ residual.ravel()) / sigma**2
    negative_hessian = (jacobian.T @ jacobian) / sigma**2

    if regularization > 0.0:
        negative_hessian = (
            negative_hessian + regularization * np.eye(len(PARAMETER_NAMES))
        )

    hessian = -negative_hessian
    eigenvalues = np.linalg.eigvalsh(negative_hessian)
    condition_number = float(np.linalg.cond(negative_hessian))

    # Use the pseudoinverse because a parameter direction may be locally
    # unidentifiable, in which case the negative Hessian is singular.
    covariance = np.linalg.pinv(negative_hessian, hermitian=True)

    return CurvatureResult(
        data=data,
        rendered=rendered,
        residual=residual,
        jacobian=jacobian,
        derivative_images=derivative_images,
        gradient_log_likelihood=gradient,
        negative_hessian=negative_hessian,
        hessian_log_likelihood=hessian,
        covariance=covariance,
        precision_eigenvalues=eigenvalues,
        condition_number=condition_number,
    )


def main() -> None:
    """Choose an atom and compute its local posterior curvature.

    Args:
        None.

    Returns:
        None.
    """
    # -------------------------------------------------------------------------
    # User choices
    # -------------------------------------------------------------------------
    scene_path = DATA_DIR / "scene.npz"
    output_path = BASIN_DIR / "atom_curvature.npz"

    sigma = 0.02
    regularization = 0.0
    check_finite_differences = True
    finite_difference_relative_step = 1e-5

    atom = Atom(
        x0=25.0,
        depth=1.5,
        R=0.10,
        amplitude=0.8,
        eps_r=1.0,
    )

    # -------------------------------------------------------------------------
    # Curvature calculation
    # -------------------------------------------------------------------------
    scene = Scene.load(scene_path)
    result = compute_atom_curvature(
        sigma,
        atom,
        scene,
        regularization=regularization,
    )

    print("Parameter order:", PARAMETER_NAMES)
    print("Gradient of log likelihood:")
    print(result.gradient_log_likelihood)
    print("\nNegative Hessian / precision:")
    print(result.negative_hessian)
    print("\nLocal covariance (Moore--Penrose inverse of precision):")
    print(result.covariance)
    print("\nPrecision eigenvalues:")
    print(result.precision_eigenvalues)
    print(f"Condition number: {result.condition_number:.6g}")
    print(f"Residual L2 norm: {np.linalg.norm(result.residual):.6g}")

    # Compare the analytic Jacobian against central finite differences.
    if check_finite_differences:
        theta = np.array(
            [atom.x0, atom.depth, atom.R, atom.amplitude],
            dtype=float,
        )
        step_sizes = finite_difference_relative_step * np.maximum(
            1.0,
            np.abs(theta),
        )

        # Keep the central radius perturbation inside the support R >= 0.
        if atom.R > 0.0:
            step_sizes[2] = min(step_sizes[2], 0.25 * atom.R)

        numeric_jacobian = finite_difference_atom_jacobian(
            atom,
            scene,
            step_sizes,
        )
        difference = result.jacobian - numeric_jacobian
        relative_error = np.linalg.norm(difference) / max(
            np.linalg.norm(numeric_jacobian),
            np.finfo(float).eps,
        )
        maximum_absolute_error = float(np.max(np.abs(difference)))

        print("\nFinite-difference check:")
        print("  step sizes:", step_sizes)
        print(f"  relative Frobenius error: {relative_error:.6g}")
        print(f"  maximum absolute error:   {maximum_absolute_error:.6g}")

    # -------------------------------------------------------------------------
    # Save results
    # -------------------------------------------------------------------------
    output_path.parent.mkdir(parents=True, exist_ok=True)
    np.savez_compressed(
        output_path,
        parameter_names=np.array(PARAMETER_NAMES),
        atom=np.array([atom.x0, atom.depth, atom.R, atom.amplitude]),
        sigma=sigma,
        data=result.data,
        rendered=result.rendered,
        residual=result.residual,
        jacobian=result.jacobian,
        derivative_images=result.derivative_images,
        gradient_log_likelihood=result.gradient_log_likelihood,
        negative_hessian=result.negative_hessian,
        hessian_log_likelihood=result.hessian_log_likelihood,
        covariance=result.covariance,
        precision_eigenvalues=result.precision_eigenvalues,
        condition_number=result.condition_number,
    )
    print(f"\nSaved results to {output_path.resolve()}")


if __name__ == "__main__":
    main()
