"""Given a single atom, compute the Hessian of the log of the posterior 
at that atom, where the data generated by that atom is treated as the observed data. 
To compute the Hessian, the Jacobian of the forward map is computed analytically.

For an atom theta = (x0, depth, R, amplitude), we compute

    J[k, m] = d vec(A(theta))[k] / d theta[m]

analytically, then forms the negative Hessian of the log of the posterior at that atom

    -d^2 log p(theta | data) / d theta^2  =  J.T @ J / sigma**2.

Example
-------
python basin_distribution.py \
    --scene ../data/birth_scene.npz \
    --sigma 0.02 \
    --x0 25.0 --depth 1.5 --radius 0.10 --amplitude 0.8 \
    --output atom_curvature.npz --check-finite-differences
"""

from __future__ import annotations

import argparse
from dataclasses import dataclass
from pathlib import Path

import numpy as np

from bayesian_gpr import Atom, Scene
from bayesian_gpr.forward import render_atom


PARAMETER_NAMES = ("x0", "depth", "R", "amplitude")


@dataclass(frozen=True)
class CurvatureResult:
    """Outputs of the one-atom local-curvature calculation."""

    rendered: np.ndarray
    residual: np.ndarray
    jacobian: np.ndarray
    derivative_images: np.ndarray
    gradient_log_likelihood: np.ndarray
    negative_hessian_gauss_newton: np.ndarray
    hessian_log_likelihood_gauss_newton: np.ndarray
    covariance: np.ndarray
    precision_eigenvalues: np.ndarray
    condition_number: float


def _ricker_and_derivative(tau: np.ndarray, f0: float) -> tuple[np.ndarray, np.ndarray]:
    """Return the Ricker wavelet and its derivative with respect to ``tau``."""
    c2 = (np.pi * f0) ** 2
    u = c2 * tau**2
    exp_minus_u = np.exp(-u)
    wavelet = (1.0 - 2.0 * u) * exp_minus_u
    wavelet_prime = 2.0 * c2 * tau * (2.0 * u - 3.0) * exp_minus_u
    return wavelet, wavelet_prime


def analytic_atom_jacobian(atom: Atom, scene: Scene) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """Render one atom and compute its analytic Jacobian.

    Parameters
    ----------
    atom:
        Atom whose parameters are ordered as ``(x0, depth, R, amplitude)``.
    scene:
        Supplies the grid, wavelet and soil parameters used by ``render_atom``.

    Returns
    -------
    rendered:
        Array of shape ``(Nt, Nx)``.
    jacobian:
        Matrix of shape ``(Nt * Nx, 4)``.
    derivative_images:
        Array of shape ``(4, Nt, Nx)`` in ``PARAMETER_NAMES`` order.
    """
    x_axis = np.asarray(scene.grid.x_axis, dtype=float)
    t_axis = np.asarray(scene.grid.t_axis, dtype=float)
    v = float(scene.soil.v)
    alpha = float(scene.soil.alpha)
    f0 = float(scene.wavelet.f0)

    p = float(atom.depth + atom.R)
    if p <= 0.0:
        raise ValueError("The analytic formula requires depth + R > 0.")
    if v <= 0.0:
        raise ValueError("Soil velocity must be positive.")

    delta = x_axis - float(atom.x0)                    # (Nx,)
    q = np.sqrt(p**2 + delta**2)                       # one-way slant range

    spread = np.sqrt(p / q)
    absorb = np.exp(-2.0 * alpha * q)
    attenuation = spread * absorb                     # B_j

    # Same locus as bayesian_gpr.forward.render_atom:
    # T_j = 2/v * (q_j - p) + 2*depth/v.
    t_locus = (2.0 / v) * (q - p) + (2.0 * atom.depth / v)
    tau = t_axis[:, None] - t_locus[None, :]

    wavelet, wavelet_prime = _ricker_and_derivative(tau, f0)
    amplitude = float(atom.amplitude)
    rendered = amplitude * attenuation[None, :] * wavelet

    # Derivatives of log attenuation B_j = sqrt(p/q_j) exp(-2 alpha q_j).
    dlogB_dx0 = delta * (0.5 / q**2 + 2.0 * alpha / q)
    dlogB_dp = 0.5 / p - 0.5 * p / q**2 - 2.0 * alpha * p / q

    # Derivatives of tau = t - T.
    dtau_dx0 = 2.0 * delta / (v * q)
    dtau_ddepth = -2.0 * p / (v * q)
    dtau_dR = (2.0 / v) * (1.0 - p / q)

    common = amplitude * attenuation[None, :]
    dA_dx0 = common * (
        wavelet * dlogB_dx0[None, :]
        + wavelet_prime * dtau_dx0[None, :]
    )
    dA_ddepth = common * (
        wavelet * dlogB_dp[None, :]
        + wavelet_prime * dtau_ddepth[None, :]
    )
    dA_dR = common * (
        wavelet * dlogB_dp[None, :]
        + wavelet_prime * dtau_dR[None, :]
    )
    dA_damplitude = attenuation[None, :] * wavelet

    derivative_images = np.stack(
        (dA_dx0, dA_ddepth, dA_dR, dA_damplitude), axis=0
    )
    jacobian = derivative_images.reshape(4, -1).T
    return rendered, jacobian, derivative_images


def finite_difference_atom_jacobian(
    atom: Atom,
    scene: Scene,
    step_sizes: np.ndarray,
) -> np.ndarray:
    """Compute a central-finite-difference Jacobian for validation."""
    step_sizes = np.asarray(step_sizes, dtype=float)
    if step_sizes.shape != (4,) or np.any(step_sizes <= 0.0):
        raise ValueError("step_sizes must contain four positive values.")

    theta = np.array([atom.x0, atom.depth, atom.R, atom.amplitude], dtype=float)
    jacobian = np.empty((scene.grid.Nt * scene.grid.Nx, 4), dtype=float)

    def make_atom(values: np.ndarray) -> Atom:
        return Atom(
            x0=float(values[0]),
            depth=float(values[1]),
            R=float(values[2]),
            amplitude=float(values[3]),
            eps_r=atom.eps_r,
        )

    for k, h in enumerate(step_sizes):
        plus = theta.copy()
        minus = theta.copy()
        plus[k] += h
        minus[k] -= h

        if k == 2 and minus[k] < 0.0:
            raise ValueError("Radius finite-difference step crosses R=0.")

        image_plus = render_atom(
            make_atom(plus), scene.grid, scene.wavelet, scene.soil
        )
        image_minus = render_atom(
            make_atom(minus), scene.grid, scene.wavelet, scene.soil
        )
        jacobian[:, k] = ((image_plus - image_minus) / (2.0 * h)).ravel()

    return jacobian


def compute_atom_curvature(
    data: np.ndarray,
    sigma: float,
    atom: Atom,
    scene: Scene,
    *,
    regularization: float = 0.0,
) -> CurvatureResult:
    """Compute the Jacobian, likelihood gradient, Hessian and local covariance.

    The Gaussian log likelihood is

        ell(theta) = -||A(theta) - data||^2 / (2 sigma^2).

    The returned Hessian is the Gauss--Newton approximation

        H_ell ~= -J.T J / sigma^2.

    At zero residual this equals the exact likelihood Hessian.  Interior uniform
    priors and the exponential radius prior add no Hessian curvature, so this is
    also the local log-posterior Hessian for the priors used in ``birth_mcmc.py``.
    """
    data = np.asarray(data, dtype=float)
    if data.shape != (scene.grid.Nt, scene.grid.Nx):
        raise ValueError(
            f"data has shape {data.shape}; expected "
            f"({scene.grid.Nt}, {scene.grid.Nx})."
        )
    if not np.isfinite(data).all():
        raise ValueError("data contains non-finite values.")
    if sigma <= 0.0 or not np.isfinite(sigma):
        raise ValueError("sigma must be finite and positive.")
    if regularization < 0.0:
        raise ValueError("regularization must be nonnegative.")

    rendered, jacobian, derivative_images = analytic_atom_jacobian(atom, scene)
    residual = rendered - data

    gradient = -(jacobian.T @ residual.ravel()) / sigma**2
    precision = (jacobian.T @ jacobian) / sigma**2
    if regularization:
        precision = precision + regularization * np.eye(4)

    hessian = -precision
    eigenvalues = np.linalg.eigvalsh(precision)
    condition_number = float(np.linalg.cond(precision))

    # pinv remains useful when a parameter direction is locally unidentifiable.
    covariance = np.linalg.pinv(precision, hermitian=True)

    return CurvatureResult(
        rendered=rendered,
        residual=residual,
        jacobian=jacobian,
        derivative_images=derivative_images,
        gradient_log_likelihood=gradient,
        negative_hessian_gauss_newton=precision,
        hessian_log_likelihood_gauss_newton=hessian,
        covariance=covariance,
        precision_eigenvalues=eigenvalues,
        condition_number=condition_number,
    )


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--scene", type=Path, required=True, help="Scene .npz file.")
    parser.add_argument("--sigma", type=float, required=True, help="Noise standard deviation.")
    parser.add_argument("--x0", type=float, required=True)
    parser.add_argument("--depth", type=float, required=True)
    parser.add_argument("--radius", type=float, required=True)
    parser.add_argument("--amplitude", type=float, required=True)
    parser.add_argument("--eps-r", type=float, default=1.0)
    parser.add_argument(
        "--synthetic-data",
        action="store_true",
        help="Use A(atom) as DATA instead of scene.observed(); gives zero residual.",
    )
    parser.add_argument(
        "--regularization",
        type=float,
        default=0.0,
        help="Optional diagonal ridge added to J.T J / sigma^2.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("atom_curvature.npz"),
        help="Output .npz path.",
    )
    parser.add_argument(
        "--check-finite-differences",
        action="store_true",
        help="Compare the analytic Jacobian with central finite differences.",
    )
    parser.add_argument(
        "--fd-relative-step",
        type=float,
        default=1e-5,
        help="Relative step used for the finite-difference check.",
    )
    return parser.parse_args()


def main() -> None:
    args = _parse_args()
    scene = Scene.load(args.scene)
    atom = Atom(
        x0=args.x0,
        depth=args.depth,
        R=args.radius,
        amplitude=args.amplitude,
        eps_r=args.eps_r,
    )

    if args.synthetic_data:
        data = render_atom(atom, scene.grid, scene.wavelet, scene.soil)
    else:
        data = scene.observed()

    result = compute_atom_curvature(
        data,
        args.sigma,
        atom,
        scene,
        regularization=args.regularization,
    )

    print("Parameter order:", PARAMETER_NAMES)
    print("Gradient of log likelihood:")
    print(result.gradient_log_likelihood)
    print("\nNegative Gauss--Newton Hessian / precision:")
    print(result.negative_hessian_gauss_newton)
    print("\nLocal covariance (Moore--Penrose inverse of precision):")
    print(result.covariance)
    print("\nPrecision eigenvalues:")
    print(result.precision_eigenvalues)
    print(f"Condition number: {result.condition_number:.6g}")
    print(f"Residual L2 norm: {np.linalg.norm(result.residual):.6g}")

    if args.check_finite_differences:
        theta = np.array([atom.x0, atom.depth, atom.R, atom.amplitude])
        steps = args.fd_relative_step * np.maximum(1.0, np.abs(theta))
        # Keep the central radius perturbation inside R >= 0.
        if atom.R > 0.0:
            steps[2] = min(steps[2], 0.25 * atom.R)
        numeric = finite_difference_atom_jacobian(atom, scene, steps)
        difference = result.jacobian - numeric
        relative_error = np.linalg.norm(difference) / max(
            np.linalg.norm(numeric), np.finfo(float).eps
        )
        max_abs_error = np.max(np.abs(difference))
        print("\nFinite-difference check:")
        print("  step sizes:", steps)
        print(f"  relative Frobenius error: {relative_error:.6g}")
        print(f"  maximum absolute error:   {max_abs_error:.6g}")

    args.output.parent.mkdir(parents=True, exist_ok=True)
    np.savez_compressed(
        args.output,
        parameter_names=np.array(PARAMETER_NAMES),
        atom=np.array([atom.x0, atom.depth, atom.R, atom.amplitude]),
        sigma=args.sigma,
        data=data,
        rendered=result.rendered,
        residual=result.residual,
        jacobian=result.jacobian,
        derivative_images=result.derivative_images,
        gradient_log_likelihood=result.gradient_log_likelihood,
        negative_hessian_gauss_newton=result.negative_hessian_gauss_newton,
        hessian_log_likelihood_gauss_newton=result.hessian_log_likelihood_gauss_newton,
        covariance=result.covariance,
        precision_eigenvalues=result.precision_eigenvalues,
        condition_number=result.condition_number,
    )
    print(f"\nSaved results to {args.output.resolve()}")


if __name__ == "__main__":
    main()
