"""Compute a single atom, compute the Laplace approximation to the posterior at that atom.

The observed data are always defined to be the noise-free data generated by the
chosen atom. Therefore, at the chosen atom, the exact Hessian of the log 
likelihood is

    d^2 log p(data | theta) / d theta^2 = -J.T @ J / sigma**2,

where ``J`` is the analytic Jacobian of the forward map with respect to
``theta = (x0, depth, R, amplitude)``. The exponential radius prior contributes
a nonzero gradient but zero Hessian curvature. The Laplace approximation to 
the posterior, a local Gaussian approximation to the posterior, therefore 
has Hessian equal to the Hessian of the log likelihood and has mean 

    mean = theta + covariance @ gradient_log_posterior.

The atom, noise level, scene path, and output path are all chosen directly in ``main``.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

import numpy as np

from bayesian_gpr import Atom, Scene
from bayesian_gpr.forward import render_atom


BASIN_DIR = Path(__file__).resolve().parent
DATA_DIR = BASIN_DIR / "data"

PARAMETER_NAMES = ("x0", "depth", "R", "amplitude")


@dataclass(frozen=True)
class CurvatureResult:
    """Store the outputs of the one-atom curvature calculation.

    Attributes:
        data: Synthetic data generated by the chosen atom.
        rendered: Forward-map output evaluated at the chosen atom.
        residual: Difference between ``rendered`` and ``data``.
        jacobian: Analytic forward-map Jacobian with shape ``(Nt * Nx, 4)``.
        gradient_log_likelihood: Gradient of the Gaussian log likelihood.
        gradient_log_prior: Gradient of the log prior.
        gradient_log_posterior: Gradient of the log posterior.
        mean: Mean of the Laplace approximation to the posterior.
        negative_hessian: Negative Hessian of the log posterior.
        hessian_log_likelihood: Hessian of the log likelihood.
        covariance: Moore--Penrose inverse of the negative Hessian.
        precision_eigenvalues: Eigenvalues of the negative Hessian.
        condition_number: Condition number of the negative Hessian.
    """

    data: np.ndarray
    rendered: np.ndarray
    residual: np.ndarray
    jacobian: np.ndarray
    gradient_log_likelihood: np.ndarray
    gradient_log_prior: np.ndarray
    gradient_log_posterior: np.ndarray
    mean: np.ndarray
    negative_hessian: np.ndarray
    hessian_log_likelihood: np.ndarray
    covariance: np.ndarray
    precision_eigenvalues: np.ndarray
    condition_number: float


def ricker_and_derivative(
    tau: np.ndarray,
    f0: float,
) -> tuple[np.ndarray, np.ndarray]:
    """Return the Ricker wavelet and its derivative with respect to time offset.

    Args:
        tau: Time offsets in seconds.
        f0: Centre frequency in Hz.

    Returns:
        Ricker-wavelet values and their derivatives with respect to ``tau``.
    """
    c_squared = (np.pi * f0) ** 2
    u = c_squared * tau**2
    exp_minus_u = np.exp(-u)

    wavelet = (1.0 - 2.0 * u) * exp_minus_u
    wavelet_derivative = (
        2.0 * c_squared * tau * (2.0 * u - 3.0) * exp_minus_u
    )
    return wavelet, wavelet_derivative


def analytic_atom_jacobian(
    atom: Atom,
    scene: Scene,
) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """Render one atom and compute the analytic forward-map Jacobian.

    The parameter order is ``(x0, depth, R, amplitude)``. Each column of the
    Jacobian is the vectorised derivative image for one parameter.

    Args:
        atom: Atom at which to evaluate the forward map and its derivatives.
        scene: Scene supplying the grid, wavelet, and soil parameters.

    Returns:
        Rendered one-atom B-scan and analytic Jacobian.
    """
    x_axis = np.asarray(scene.grid.x_axis, dtype=float)
    t_axis = np.asarray(scene.grid.t_axis, dtype=float)
    velocity = float(scene.soil.v)
    alpha = float(scene.soil.alpha)
    f0 = float(scene.wavelet.f0)

    effective_depth = float(atom.depth + atom.R)
    if effective_depth <= 0.0:
        raise ValueError("Atom depth + radius must be positive")
    if velocity <= 0.0:
        raise ValueError("Soil velocity must be positive")

    horizontal_offset = x_axis - float(atom.x0)
    slant_range = np.sqrt(effective_depth**2 + horizontal_offset**2)

    spread = np.sqrt(effective_depth / slant_range)
    absorption = np.exp(-2.0 * alpha * slant_range)
    attenuation = spread * absorption

    # This is the same travel-time locus used by render_atom.
    travel_time = (
        (2.0 / velocity) * (slant_range - effective_depth)
        + (2.0 * atom.depth / velocity)
    )
    tau = t_axis[:, None] - travel_time[None, :]

    wavelet, wavelet_derivative = ricker_and_derivative(tau, f0)
    amplitude = float(atom.amplitude)
    rendered = amplitude * attenuation[None, :] * wavelet

    # Derivatives of log(B), where
    # B = sqrt(effective_depth / slant_range) * exp(-2 alpha slant_range).
    dlog_attenuation_dx0 = horizontal_offset * (
        0.5 / slant_range**2 + 2.0 * alpha / slant_range
    )
    dlog_attenuation_deffective_depth = (
        0.5 / effective_depth
        - 0.5 * effective_depth / slant_range**2
        - 2.0 * alpha * effective_depth / slant_range
    )

    # Since tau = t - travel_time, these are the derivatives of tau.
    dtau_dx0 = 2.0 * horizontal_offset / (velocity * slant_range)
    dtau_ddepth = -2.0 * effective_depth / (velocity * slant_range)
    dtau_dR = (2.0 / velocity) * (
        1.0 - effective_depth / slant_range
    )

    common = amplitude * attenuation[None, :]

    dA_dx0 = common * (
        wavelet * dlog_attenuation_dx0[None, :]
        + wavelet_derivative * dtau_dx0[None, :]
    )
    dA_ddepth = common * (
        wavelet * dlog_attenuation_deffective_depth[None, :]
        + wavelet_derivative * dtau_ddepth[None, :]
    )
    dA_dR = common * (
        wavelet * dlog_attenuation_deffective_depth[None, :]
        + wavelet_derivative * dtau_dR[None, :]
    )
    dA_damplitude = attenuation[None, :] * wavelet

    derivative_images = np.stack(
        (dA_dx0, dA_ddepth, dA_dR, dA_damplitude),
        axis=0,
    )
    jacobian = derivative_images.reshape(4, -1).T

    return rendered, jacobian


def compute_atom_curvature(
    sigma: float,
    atom: Atom,
    scene: Scene,
    *,
    lambda_r: float = 10.0,
) -> CurvatureResult:
    """Compute the one-atom Jacobian, Hessian, and local covariance.

    The data are always generated from the same atom at which the derivatives
    are evaluated:

        data = A(atom).

    Consequently, the residual is zero and the exact Hessian of the Gaussian
    log likelihood is ``-J.T @ J / sigma**2``. The interior uniform priors add
    no gradient or Hessian curvature. The exponential radius prior has log
    density ``constant - lambda_r * R``. It therefore contributes ``-lambda_r``
    to the radius component of the gradient, but contributes no Hessian curvature.

    Completing the square gives the recentered local Gaussian

        N(mean, covariance),

    where ``mean = theta + covariance @ gradient_log_posterior``.

    Args:
        sigma: Standard deviation of the additive Gaussian noise model.
        atom: Representative atom defining both the synthetic data and the
            point at which curvature is calculated.
        scene: Scene supplying the grid, wavelet, and soil parameters.
        lambda_r: Rate of the exponential prior on the radius.

    Returns:
        One-atom curvature results.
    """
    if sigma <= 0.0 or not np.isfinite(sigma):
        raise ValueError("sigma must be finite and positive")
    if lambda_r < 0.0 or not np.isfinite(lambda_r):
        raise ValueError("lambda_r must be finite and nonnegative")

    # The analytic renderer and render_atom should agree. We use render_atom to
    # define the synthetic observed data exactly as the model code does.
    data = render_atom(atom, scene.grid, scene.wavelet, scene.soil)
    rendered, jacobian = analytic_atom_jacobian(atom, scene)
    residual = rendered - data

    gradient_log_likelihood = -(jacobian.T @ residual.ravel()) / sigma**2

    # The only nonconstant interior prior term is -lambda_r * R.
    gradient_log_prior = np.zeros(len(PARAMETER_NAMES), dtype=float)
    gradient_log_prior[2] = -lambda_r
    gradient_log_posterior = gradient_log_likelihood + gradient_log_prior

    negative_hessian = (jacobian.T @ jacobian) / sigma**2

    hessian = -negative_hessian
    eigenvalues = np.linalg.eigvalsh(negative_hessian)
    condition_number = float(np.linalg.cond(negative_hessian))

    # Use the pseudoinverse because a parameter direction may be locally
    # unidentifiable, in which case the negative Hessian is singular.
    covariance = np.linalg.pinv(negative_hessian, hermitian=True)

    theta = np.array(
        [atom.x0, atom.depth, atom.R, atom.amplitude],
        dtype=float,
    )
    mean = theta + covariance @ gradient_log_posterior

    return CurvatureResult(
        data=data,
        rendered=rendered,
        residual=residual,
        jacobian=jacobian,
        gradient_log_likelihood=gradient_log_likelihood,
        gradient_log_prior=gradient_log_prior,
        gradient_log_posterior=gradient_log_posterior,
        mean=mean,
        negative_hessian=negative_hessian,
        hessian_log_likelihood=hessian,
        covariance=covariance,
        precision_eigenvalues=eigenvalues,
        condition_number=condition_number,
    )


def main() -> None:
    """Choose an atom and compute its local posterior curvature.

    Args:
        None.

    Returns:
        None.
    """
    # -------------------------------------------------------------------------
    # User choices
    # -------------------------------------------------------------------------
    scene_path = DATA_DIR / "scene.npz"
    output_path = BASIN_DIR / "atom_curvature.npz"

    sigma = 0.02
    lambda_r = 10.0

    atom = Atom(
        x0=25.0,
        depth=1.5,
        R=0.10,
        amplitude=0.8,
        eps_r=1.0,
    )

    # -------------------------------------------------------------------------
    # Curvature calculation
    # -------------------------------------------------------------------------
    scene = Scene.load(scene_path)
    result = compute_atom_curvature(
        sigma,
        atom,
        scene,
        lambda_r=lambda_r,
    )

    print("Parameter order:", PARAMETER_NAMES)
    print("Representative atom:")
    print(np.array([atom.x0, atom.depth, atom.R, atom.amplitude]))
    print("\nGradient of log likelihood:")
    print(result.gradient_log_likelihood)
    print("\nGradient of log prior:")
    print(result.gradient_log_prior)
    print("\nGradient of log posterior:")
    print(result.gradient_log_posterior)
    print("\nRecentered Gaussian mean:")
    print(result.mean)
    print("\nNegative Hessian / precision:")
    print(result.negative_hessian)
    print("\nLocal covariance (Moore--Penrose inverse of precision):")
    print(result.covariance)
    print("\nPrecision eigenvalues:")
    print(result.precision_eigenvalues)
    print(f"Condition number: {result.condition_number:.6g}")
    print(f"Residual L2 norm: {np.linalg.norm(result.residual):.6g}")

    # -------------------------------------------------------------------------
    # Save results
    # -------------------------------------------------------------------------
    output_path.parent.mkdir(parents=True, exist_ok=True)
    np.savez_compressed(
        output_path,
        parameter_names=np.array(PARAMETER_NAMES),
        atom=np.array([atom.x0, atom.depth, atom.R, atom.amplitude]),
        sigma=sigma,
        lambda_r=lambda_r,
        mean=result.mean,
        data=result.data,
        rendered=result.rendered,
        residual=result.residual,
        jacobian=result.jacobian,
        gradient_log_likelihood=result.gradient_log_likelihood,
        gradient_log_prior=result.gradient_log_prior,
        gradient_log_posterior=result.gradient_log_posterior,
        negative_hessian=result.negative_hessian,
        hessian_log_likelihood=result.hessian_log_likelihood,
        covariance=result.covariance,
        precision_eigenvalues=result.precision_eigenvalues,
        condition_number=result.condition_number,
    )
    print(f"\nSaved results to {output_path.resolve()}")


if __name__ == "__main__":
    main()